# Shared syllabus renderer (HTML + PDF + GitHub markdown).
#
# Not run directly. Each course keeps a two-line render.R that sources this
# file and calls render_syllabus() with its own output directory:
#
#   here <- dirname(sub("^--file=", "", grep("^--file=", commandArgs(), value = TRUE)[1]))
#   source(file.path(here, "..", "..", "_syllabus-template", "render.R"))
#   render_syllabus(file.path(here, "syllabus", "syllabus.Rmd"),
#                   "/path/to/jcervas.github.io/teaching/2026-2027/class-cmu-2026-84-309")
#
# Replaces a bare rmarkdown::render() call, because the self-contained HTML
# needs one repair afterwards — see fix_base64_uris() below.

# pandoc 2.19.1 encodes --embed-resources data URIs with the URL-safe base64
# alphabet ("-" and "_" instead of "+" and "/"). Browsers reject those, so every
# embedded figure renders as a broken image. Translate the payloads back to
# standard base64. Harmless once pandoc is upgraded past the bug — standard
# payloads contain no "-" or "_" to begin with.
fix_base64_uris <- function(html_file) {
  if (!file.exists(html_file)) return(invisible(FALSE))
  txt <- paste(readLines(html_file, warn = FALSE), collapse = "\n")
  pat <- "(?<=;base64,)[A-Za-z0-9+/=_-]{40,}"
  m <- gregexpr(pat, txt, perl = TRUE)
  payloads <- regmatches(txt, m)[[1]]
  n <- sum(grepl("[-_]", payloads))
  regmatches(txt, m) <- list(chartr("-_", "+/", payloads))
  writeLines(txt, html_file)
  message(sprintf("  repaired %d URL-safe base64 data URI(s) in %s", n, basename(html_file)))
  invisible(TRUE)
}

# Rendering into an absolute `output_dir` makes knitr write absolute figure
# paths into the markdown: an <img src="/Users/.../readme_files/figure-gfm/
# plot-1.png"> resolves on the machine that built it and nowhere else, so every
# figure in the published GitHub markdown is a broken image. The figure folder
# sits beside the .md, so the fix is to drop the directory prefix and leave the
# path relative. Percent-encoded prefixes ("/My%20Drive/") are matched too, and
# so is a file:// scheme, because pandoc emits either depending on the format.
relativize_figure_paths <- function(md_file) {
  if (!file.exists(md_file)) return(invisible(FALSE))
  txt <- paste(readLines(md_file, warn = FALSE), collapse = "\n")
  # Two contexts, two rules. Inside an attribute the path may contain literal
  # spaces ("/My Drive/"), so anything up to the closing quote counts; inside a
  # markdown (...) pandoc percent-encodes them, so stopping at whitespace is
  # right and keeps the pattern from running past the closing paren.
  pats <- c('(src=")(?:file://)?/[^"]*?/([^/"]+_files/)',
            '(\\()(?:file://)?/[^()\\s]*?/([^/()\\s]+_files/)')
  n <- 0L
  for (p in pats) {
    hits <- gregexpr(p, txt, perl = TRUE)[[1]]
    if (hits[1] != -1) n <- n + length(hits)
    txt <- gsub(p, "\\1\\2", txt, perl = TRUE)
  }
  if (n == 0L) return(invisible(FALSE))
  writeLines(txt, md_file)
  message(sprintf("  made %d figure path(s) relative in %s", n, basename(md_file)))
  invisible(TRUE)
}

# What actually feeds a build: the source, the section files it pulls in as
# child chunks, and the shared theme/renderer. Deliberately NOT everything in
# the course folder — assignments/*.md are Canvas's source of truth and never
# reach the syllabus, so including them would cry stale on every Canvas edit.
syllabus_inputs <- function(src) {
  # The document and its sections live together in <course>/<term>/syllabus/,
  # with the shared theme three levels up. README.md documents the folder and
  # course-meta.tex is generated below — neither is an input.
  d <- dirname(src)
  tmpl <- file.path(d, "..", "..", "..", "_syllabus-template")
  sections <- list.files(d, "[.](Rmd|md|csl|bib)$", full.names = TRUE,
                         ignore.case = TRUE)
  sections <- sections[base::basename(sections) != "README.md"]
  files <- c(src, sections, list.files(tmpl, "[.](R|css)$", full.names = TRUE))
  files[file.exists(files)]
}

# The PDF running head needs a short course name and the term. Both are already
# in the YAML (runningheader/title, subtitle), so writing them a second time by
# hand in course-meta.tex meant two files to edit every term — and one of them
# silently wrong if you forgot. Generate it instead.
write_course_meta <- function(src) {
  y <- rmarkdown::yaml_front_matter(src)
  name <- if (!is.null(y$runningheader)) y$runningheader else y$title
  term <- if (is.null(y$subtitle)) "" else y$subtitle
  term <- gsub("[][]", "", term)             # "[84-355] | Fall 2026"
  term <- gsub("\\s*\\|\\s*", " \u00b7 ", term)   # -> "84-355 · Fall 2026"
  out <- file.path(dirname(src), "course-meta.tex")
  txt <- c("% GENERATED by render.R from the YAML in syllabus.Rmd — do not edit.",
           "% Listed BEFORE syllabus-preamble.tex in the YAML in_header, which",
           "% reads these two macros for the running head.",
           sprintf("\\newcommand{\\courseName}{%s}", name),
           sprintf("\\newcommand{\\courseTerm}{%s}", term))
  old <- if (file.exists(out)) readLines(out, warn = FALSE) else character(0)
  if (!identical(old, txt)) {                # only touch it when it changes
    writeLines(txt, out, useBytes = TRUE)
    message("  wrote course-meta.tex (", name, " / ", term, ")")
  }
  invisible(out)
}

# The failure this catches: a source edited after the last build, so what sits
# in the site repo — and on the live site — is older than what it was made
# from. Nothing else notices, because the OUTPUT has not changed, so git
# reports the tree clean and the stale files publish unremarked.
check_freshness <- function(src, out_dir, basename, formats, label = "Published") {
  outs <- file.path(out_dir, paste0(basename, c(html_document = ".html",
                                                pdf_document  = ".pdf",
                                                md_document   = ".md")[formats]))
  outs <- outs[file.exists(outs)]
  if (!length(outs)) return(invisible(NULL))          # nothing built yet

  ins <- syllabus_inputs(src)
  newest <- ins[which.max(file.mtime(ins))]
  stale <- outs[file.mtime(outs) < file.mtime(newest)]
  if (!length(stale)) return(invisible(NULL))

  message(sprintf("  %s output is older than %s (%s):",
                  label, base::basename(newest),
                  format(file.mtime(newest), "%b %d %H:%M:%S")))
  for (f in stale)
    message(sprintf("    %-26s %s", base::basename(f),
                    format(file.mtime(f), "%b %d %H:%M:%S")))
  invisible(stale)
}

# Every section file opens with an editorial comment saying what it is for and
# how to edit it. Those are notes to whoever opens the file, not to the reader,
# but an HTML comment survives pandoc into every output — the published gfm
# markdown carried ten of them. Drop comment blocks that came from the body.
# Pandoc's own head includes (code folding, MathJax) are added after the filter
# runs and are untouched. Written to a tempfile so this file stays the single
# thing a course has to source.
editorial_comment_filter <- function() {
  f <- tempfile(fileext = ".lua")
  writeLines(c(
    'function RawBlock(el)',
    '  if el.format == "html" and el.text:match("^%s*<!%-%-") then',
    '    return {}',
    '  end',
    'end'), f)
  f
}

# knitr names a figure after its chunk and never cleans up: rename or delete a
# chunk and the old PNG stays in the published output, referenced by nothing.
# Two had accumulated before anyone looked. Scan what was actually published
# rather than guessing from the source.
check_orphan_figures <- function(out_dir) {
  figs <- list.files(out_dir, "[.](png|svg|pdf|jpg|jpeg)$",
                     recursive = TRUE, full.names = TRUE)
  figs <- figs[grepl("_files/", figs, fixed = TRUE)]
  if (!length(figs)) return(invisible(NULL))
  docs <- list.files(out_dir, "[.](md|html)$", full.names = TRUE)
  if (!length(docs)) return(invisible(NULL))          # nothing to check against
  txt <- paste(unlist(lapply(docs, readLines, warn = FALSE)), collapse = "\n")
  orphans <- figs[!vapply(base::basename(figs),
                          function(f) grepl(f, txt, fixed = TRUE), logical(1))]
  if (!length(orphans)) return(invisible(NULL))
  message(sprintf("  %d figure(s) in the output are referenced by nothing:",
                  length(orphans)))
  for (f in orphans)
    message(sprintf("    %s", sub(paste0("^", out_dir, "/"), "", f)))
  message("    (a renamed or deleted chunk leaves its old file behind — safe to remove)")
  invisible(orphans)
}

# `params`   — passed to rmarkdown::render(); a syllabus that declares
#              `params:` in its YAML (e.g. `full: true`) can be built in
#              variants. Omit for the YAML defaults.
# `basename` — output filename without extension. Defaults to the Rmd's own
#              name; set it when building a variant so the files sit side by
#              side ("readme" and "syllabus-abridged") instead of overwriting.
# `output_options` — a list KEYED BY FORMAT NAME, e.g.
#              list(html_document = list(toc = FALSE)). Needed because the two
#              variants of one source want different YAML: the full syllabus
#              carries a table of contents and the barebones one must not.
#              A format with no entry gets NULL, which is what render() expects.
render_syllabus <- function(src, out_dir,
                            formats = c("html_document", "pdf_document", "md_document"),
                            params = NULL,
                            basename = NULL,
                            output_options = NULL) {
  stopifnot(file.exists(src))
  if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)
  if (is.null(basename)) basename <- tools::file_path_sans_ext(base::basename(src))

  ext <- c(html_document = ".html", pdf_document = ".pdf", md_document = ".md")
  write_course_meta(src)

  # Before overwriting it, report whether what is currently published was built
  # from an older source than the one on disk.
  check_freshness(src, out_dir, basename, formats)

  lua <- editorial_comment_filter()
  for (fmt in formats) {
    message("Rendering ", fmt, if (!is.null(params)) " (variant)", " ...")
    # Each render gets a fresh environment. Without it, knitr evaluates in
    # this function's frame, where the `params` argument shadows the params
    # object render() needs to create — and successive variants would also
    # leak state into one another.
    opts <- output_options[[fmt]]
    opts$pandoc_args <- c(opts$pandoc_args, "--lua-filter", lua)
    rmarkdown::render(src, output_format = fmt, output_dir = out_dir,
                      output_file = paste0(basename, ext[[fmt]]),
                      params = params, output_options = opts,
                      quiet = TRUE,
                      envir = new.env(parent = globalenv()))
  }

  if ("html_document" %in% formats) {
    fix_base64_uris(file.path(out_dir, paste0(basename, ".html")))
  }
  if ("md_document" %in% formats) {
    relativize_figure_paths(file.path(out_dir, paste0(basename, ".md")))
  }

  # And afterwards every output must be newer than every input. If one is not,
  # that format did not actually rebuild.
  if (!is.null(check_freshness(src, out_dir, basename, formats,
                               label = "WARNING: freshly built")))
    warning("render_syllabus(): an output did not rebuild — see above", call. = FALSE)

  check_orphan_figures(out_dir)

  message("Done. Output in:\n  ", out_dir)
  invisible(out_dir)
}
